version: '3.7'

services:
  mongo:
    env_file: ./.env 
    image: "mongo:${MONGO_IMAGE_VERSION}"
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    ports: 
      - "${MONGO_PORT}:27017"
    environment: 
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data:/data/db
    networks:
      - mongo-network
  mongo-express:
    env_file: ./.env
    image: "mongo-express:${ME_IMAGE_VERSION}"
    container_name: ${ME_CONTAINER_NAME}
    ports:
      - "${ME_PORT}:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    links:
      - mongo
    networks:
      - mongo-network

networks: 
  mongo-network:
    driver: bridge